module.exports.MEMBER_ROLE = {
  GUEST: 0,
  CUSTOMER: 1,
  SUPER_ADMIN: 2,
  ADMIN: 3,
  CUSTOMER_SUPPORT: 4,
};

module.exports.ORDER_STATUS = {
  ORDER_CREATED: 1,
  ORDER_IN_PROGRESS: 2,
  ORDER_COMPLETED: 3,
  ORDER_PENDING_CANCEL: 4,
  ORDER_CANCELLED: 5,
};

module.exports.PAYMENT_STATUS = {
  NOT_PAID: 1,
  VERIFIYING_PAYMENT: 2,
  PAYMENT_SUCCESS: 3,
};

module.exports.SHIPPING_STATUS = {
  PENDING: 0,
  INITIATE: 1,  
  DELIVERING: 2,
  DELIVERED: 3,
};

module.exports.PAYMENT_OPTION = {
  WALLET: 1, // points
  PAYMENT_GATEWAY: 2,
};

module.exports.PAYMENT_GATEWAY_OPTION = {
  COMMERCE_PAY: 1,
};

module.exports.MEMBER_RANK = {
  BRONZE: 1,
  SILVER: 2,
  GOLD: 3,
  DIAMOND: 4,
};

module.exports.BLOG_CONTENT_TYPE = {
  BLOG: 1,
  TUTORIAL: 2,
};


module.exports.PRODUCT_CATEGORY = {
  HEALTH_AND_WELLNESS: 1,
  FITNESS_AND_NUTRITION: 2,
  BEAUTY_AND_SKINCARE: 3,
  PERSONAL_CARE: 4,
  HOME_AND_LIFESTYLE: 5,
  ACCESSORIES: 6,
  ELECTRONICS_AND_GADGETS: 7,
  TOOLS_AND_EQUIPMENT: 8,
  SPORTS_AND_OUTDOORS: 9,
  OTHERS: 10,
};